### ISSUE TITLE
tests: close file before removing it

### ISSUE THREAD

**Issue by ltalirz** [DropD/reentry#23]
`test_file` should be closed
https://github.com/DropD/reentry/blob/396b4d1727c34be609f39af2704358d41254b94a/reentry/tests/fixtures.py#L25

See also https://stackoverflow.com/a/34717110

Noticed because this leads to errors on Windows builds
https://ci.appveyor.com/project/conda-forge/reentry-feedstock/build/1.0.14/job/op256k73tor9k38d

**Comment by DropD** [comment]
fixed in #24
