### ISSUE TITLE
populating reentry cache from python

### ISSUE THREAD

**Issue by ltalirz** [DropD/reentry#29]
This comes from @mottetm, his setup is:

 * a jupyterhub instance on a virtual machine, using LocalProcessSpawner
 * Uses the PAMAuthenticator, i.e. when a unix user A connects to the Jupyterhub and does !pwd inside a jupyter notebook it will show A's home folder
 * the ipython kernel runs inside a virtual environment located in the superuser's home folder, to which user A only has read access

He is reporting that using the `DataFactory` in the jupyter notebook does not work (i.e., for some reason, it doesn't seem to find the reentry cache).

As far as I understand, the problem is the following:
 * all packages are installed by the superuser. the reentry cache is placed in the superuser home directory
 * when user A runs stuff in jupyter notebooks, reentry looks for the reentry cache inside user A's home directory (and doesn't find one)
 * in @mottetm's setup, there is no easy way to run `reentry scan -r aiida` for the user A (which is how we currently solve this problem in AiiDA lab)

I guess there is no alternative to having a reentry cache per user, since it should reflect the user's installed packages.
I believe the solution to this is to provide a documented & supported way to populate the reentry cache directly from python (?).

**Comment by ltalirz** [comment]
Looking at what `reentry scan -r aiida` does, this should not be too difficult

https://github.com/DropD/reentry/blob/f1cd3bfc0a9af5d2c31fa7a79b9a4208c3ddc019/reentry/cli.py#L16-L35

**Comment by mottetm** [comment]
```python
from reentry import manager
manager.scan(group_re='aiida')
```

This doesn't work in `1.2.1a2` since it expects `group_re` to be a regular expression.
The variable should first be converted with `re.compile` if it is a string or an error is thrown
that the type `str` doesn't have an attribute `match`.

**Comment by ltalirz** [comment]
@DropD There should be a convenience function for this, either in reentry or in aiida.
Please let me know which oft the two you prefer.

**Comment by DropD** [comment]
I think we can put this into reentry

**Comment by ltalirz** [comment]
I overlooked that bit

> Scan only for specific PATTERNs or leave empty to scan all 

So, this should do the job, right?
```
from reentry import manager
manager.scan()
```

**Comment by mottetm** [comment]
So does this:

```python
import re
from reentry import manager
manager.scan(group_re=re.compile('aiida'))
```

I just think it would be good to have a `hasattr(group_re, 'match')` check and use `re.match` rather than `group_re.match` if the check returns false. Sure it's not essential but it would make it more user friendly.
