### ISSUE TITLE
Entry points not removed when plugin is uninstalled

### ISSUE THREAD

**Issue by greschd** [DropD/reentry#5]
When a plugin is uninstalled, the corresponding entries still remain in the data file (``js_data``). As a result, the entry points are still registered.

**Comment by DropD** [comment]
this is a known problem, there seems to be no reliable way to run custom hooks when uninstalling python packages (setuptools has no notion of uninstall, pip has no hooks).

running
``` bash
$ reentry scan
```
on the commandline should update the entry point cache and remove obsolete ones

**Comment by greschd** [comment]
Thanks! It probably makes sense to put a little section about the CLI in the README, so other people know about this as well.
