### ISSUE TITLE
python 3.9 compatibility

### ISSUE THREAD

**Issue by giovannipizzi** [DropD/reentry#57]
There is at least one point (maybe more) to check for python 3.9 compatibility.

For instance, running the AiiDA transport tests, I get this:
```
tests/transports/test_all_plugins.py::TestBasicFunctionality::test_is_open
  /Users/pizzi/.virtualenvs/aiida-dev/lib/python3.8/site-packages/reentry/jsonbackend.py:286: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
    from collections import Sequence
```
so at least this import needs to be fixed in this repository.

Pinging @ltalirz as the maintainer of this package, and @csadorf as the AiiDA dependency manager

**Comment by greschd** [comment]
Note: the `collections` removal has been postponed to Python 3.10, which is [to be released on 2021-10-04](https://www.python.org/dev/peps/pep-0619/).

So this is important to fix, but not very time critical yet.
